trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'
- script: npx -q git2semver --formatter majorminorpatch-pipelines-variables-and-label
  displayName: Generate version number (git2semver)
- script: npm version $GIT2SEMVER_MAJORMINORPATCH --no-git-tag-version
  displayName: Stamp version number (npm version)
- script: npm ci
  displayName: Restore packages (npm ci)
- script: node_modules/.bin/vsce package
  displayName: Create extension package
- task: PublishPipelineArtifact@0
  displayName: Publish VSIX artifact
  inputs:
    artifactName: drop
    targetPath: $(Build.SourcesDirectory)